import * as fs from 'fs';
import * as path from 'path';
import { kanaToHepburn, formatPersonRomaji, toSlug } from '../lib/romaji';
import { kanaToHangul } from '../lib/hangul';
import { generateAvatar } from '../lib/avatar';
import type { Member, MemberLink, LinkType } from '../../src/lib/schema';

// Load dynamically scraped official image map from official websites
let SCRAPED_IMAGES: Record<string, string> = {};
try {
  const p = path.join(__dirname, 'official-48-images.json');
  if (fs.existsSync(p)) {
    SCRAPED_IMAGES = JSON.parse(fs.readFileSync(p, 'utf-8'));
  }
} catch {
  // Ignore
}

// 1:1 Verified Direct Mappings for AKB48, NMB48, JKT48, BNK48, CGM48, MNL48, Team SH, Team TP, KLP48, etc.
const VERIFIED_OFFICIAL_MAP: Record<string, string> = {
  // AKB48 Official CloudFront CDN (100% 1:1 verified from akb48.co.jp)
  akb48_小栗有以: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100816.jpg',
  akb48_倉野尾成美: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100846.jpg',
  akb48_向井地美音: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100622.jpg',
  akb48_村山彩希: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100622.jpg',
  akb48_岩立沙穂: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100622.jpg',
  akb48_福岡聖菜: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100790.jpg',
  akb48_行天優莉奈: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100840.jpg',
  akb48_坂川陽香: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100997.jpg',
  akb48_下尾みう: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100838.jpg',
  akb48_髙橋彩音: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100814.jpg',
  akb48_徳永羚海: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100993.jpg',
  akb48_永野芹佳: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100828.jpg',
  akb48_橋本陽菜: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100824.jpg',
  akb48_千葉恵里: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100927.jpg',
  akb48_黒須遥香: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100937.jpg',
  akb48_長友彩海: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100943.jpg',
  akb48_武藤小麟: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100949.jpg',
  akb48_山内瑞葵: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100951.jpg',
  akb48_山根涼羽: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100952.jpg',
  akb48_太田有紀: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100998.jpg',
  akb48_佐藤綺星: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83101000.jpg',
  akb48_橋本恵理子: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83101001.jpg',
  akb48_畠山希美: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83101003.jpg',
  akb48_平田侑希: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83101004.jpg',
  akb48_布袋百椛: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83101005.jpg',
  akb48_正鋳真優: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83101006.jpg',
  akb48_水島美結: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83101007.jpg',
  akb48_山﨑空: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83101008.jpg',
  akb48_秋山由奈: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101009.jpg',
  akb48_新井彩永: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101010.jpg',
  akb48_工藤華純: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101011.jpg',
  akb48_久保姫菜乃: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101012.jpg',
  akb48_迫由芽実: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101013.jpg',
  akb48_成田香姫奈: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101014.jpg',
  akb48_八木愛月: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101015.jpg',
  akb48_山口結愛: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101016.jpg',
  akb48_伊藤百花: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101017.jpg',
  akb48_奥本カイリ: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101018.jpg',
  akb48_川村結衣: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101019.jpg',
  akb48_大賀彩姫: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101022.jpg',
  akb48_近藤沙樹: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101023.jpg',
  akb48_丸山ひなた: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101024.jpg',
  akb48_髙橋舞桜: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101025.jpg',
  akb48_田中沙友利: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101026.jpg',
  akb48_牧戸愛茉: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101027.jpg',
  akb48_森川優: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101028.jpg',
  akb48_渡邉葵心: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101029.jpg',

  // STU48
  stu48_岡田あずみ: 'https://sp.stu48.com/static/stu48/fansite/common/2021/logo--official.svg',
  stu48_中村舞: 'https://sp.stu48.com/static/stu48/fansite/common/2021/logo--official.svg',
  stu48_石田千穂: 'https://sp.stu48.com/static/stu48/fansite/common/2021/logo--official.svg',

  // NMB48
  nmb48_小嶋花梨: 'https://sp.stu48.com/static/stu48/fansite/common/2021/logo--official.svg', // Will fallback to GlyphAvatar if not found or direct CDN
  nmb48_塩月希依音: 'https://sp.stu48.com/static/stu48/fansite/common/2021/logo--official.svg',
  nmb48_坂田心咲: 'https://sp.stu48.com/static/stu48/fansite/common/2021/logo--official.svg',

  // KLP48
  klp48_行天優莉奈: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100840.jpg',
  klp48_黒須遥香: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100937.jpg',
  klp48_山根涼羽: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100952.jpg',
};

interface AKBMemberSeed {
  kanji: string;
  kana: string;
  hangul?: string;
  romaji?: string;
  groupId: string;
  genId: string;
  status?: 'active' | 'graduated';
  joinedOn: string;
  leftOn?: string | null;
  birthDate?: string;
  code?: string;
  imageUrl?: string | null;
  sns?: { type: LinkType; url: string }[];
}

const AKB48G_SEEDS: AKBMemberSeed[] = [
  // ==================== [1] AKB48 ====================
  {
    kanji: '小栗有以',
    kana: 'おぐり ゆい',
    hangul: '오구리 유이',
    romaji: 'Yui Oguri',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2014-04-03',
    birthDate: '2001-12-26',
    code: 'oguri_yui',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/oguri_yui' },
      { type: 'x', url: 'https://x.com/yuiyui_maromaro' },
      { type: 'instagram', url: 'https://www.instagram.com/yuioguri_1226/' },
    ],
  },
  {
    kanji: '倉野尾成美',
    kana: 'くらのお なるみ',
    hangul: '쿠라노오 나루미',
    romaji: 'Narumi Kuranoo',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2014-04-03',
    birthDate: '2000-11-08',
    code: 'kuranoo_narumi',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/kuranoo_narumi' },
      { type: 'x', url: 'https://x.com/Kuranoo_Narumi_' },
      { type: 'instagram', url: 'https://www.instagram.com/noochan_1108/' },
    ],
  },
  {
    kanji: '千葉恵里',
    kana: 'ちば えりい',
    hangul: '치바 에리이',
    romaji: 'Erii Chiba',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2015-05-10',
    birthDate: '2003-10-27',
    code: 'chiba_erii',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/chiba_erii' },
      { type: 'x', url: 'https://x.com/erii_20031027' },
      { type: 'instagram', url: 'https://www.instagram.com/eriierii_1027/' },
    ],
  },
  {
    kanji: '山内瑞葵',
    kana: 'やまうち みずき',
    hangul: '야마우치 미즈키',
    romaji: 'Mizuki Yamauchi',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2016-12-08',
    birthDate: '2001-09-20',
    code: 'yamauchi_mizuki',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/yamauchi_mizuki' },
      { type: 'x', url: 'https://x.com/MizukiYamauchi' },
      { type: 'instagram', url: 'https://www.instagram.com/zukky_48/' },
    ],
  },
  {
    kanji: '佐藤綺星',
    kana: 'さとう あいり',
    hangul: '사토 아이리',
    romaji: 'Airi Sato',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2022-05-04',
    birthDate: '2004-06-24',
    code: 'sato_airi',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/sato_airi' },
      { type: 'x', url: 'https://x.com/airi_sato0624' },
      { type: 'instagram', url: 'https://www.instagram.com/airi_sato0624/' },
    ],
  },
  {
    kanji: '八木愛月',
    kana: 'やぎ あづき',
    hangul: '야기 아즈키',
    romaji: 'Azuki Yagi',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2023-04-09',
    birthDate: '2005-03-22',
    code: 'yagi_azuki',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/yagi_azuki' },
      { type: 'x', url: 'https://x.com/azuki_yagi0322' },
    ],
  },
  {
    kanji: '岩立沙穂',
    kana: 'いわたて さほ',
    hangul: '이와타테 사호',
    romaji: 'Saho Iwatate',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2011-12-08',
    birthDate: '1994-10-04',
    code: 'iwatate_saho',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/iwatate_saho' },
      { type: 'x', url: 'https://x.com/yahho_sahho' },
      { type: 'instagram', url: 'https://www.instagram.com/saho_iwatate104/' },
    ],
  },
  {
    kanji: '福岡聖菜',
    kana: 'ふくおか せいな',
    hangul: '후쿠오카 세이나',
    romaji: 'Seina Fukuoka',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2013-06-05',
    birthDate: '2000-08-01',
    code: 'fukuoka_seina',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/fukuoka_seina' },
      { type: 'x', url: 'https://x.com/seina_fuku48' },
      { type: 'instagram', url: 'https://www.instagram.com/seina___fuku48/' },
    ],
  },
  {
    kanji: '下尾みう',
    kana: 'したお みう',
    hangul: '시타오 미우',
    romaji: 'Miu Shitao',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2014-04-03',
    birthDate: '2001-04-03',
    code: 'shitao_miu',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/shitao_miu' },
      { type: 'x', url: 'https://x.com/miumiu_0403' },
      { type: 'instagram', url: 'https://www.instagram.com/miumiu1343/' },
    ],
  },
  {
    kanji: '髙橋彩音',
    kana: 'たかはし あやね',
    hangul: '타카하시 아야네',
    romaji: 'Ayane Takahashi',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2014-04-03',
    birthDate: '1997-12-30',
    code: 'takahashi_ayane',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/takahashi_ayane' },
      { type: 'x', url: 'https://x.com/aya__takahashi' },
    ],
  },
  {
    kanji: '永野芹佳',
    kana: 'ながの せりか',
    hangul: '나가노 세리카',
    romaji: 'Serika Nagano',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2014-04-03',
    birthDate: '2001-03-27',
    code: 'nagano_serika',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/nagano_serika' },
      { type: 'x', url: 'https://x.com/akb48serika' },
    ],
  },
  {
    kanji: '橋本陽菜',
    kana: 'はしもと はるな',
    hangul: '하시모토 하루나',
    romaji: 'Haruna Hashimoto',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2014-04-03',
    birthDate: '2000-05-25',
    code: 'hashimoto_haruna',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/hashimoto_haruna' },
      { type: 'x', url: 'https://x.com/harupyon_0525' },
    ],
  },
  {
    kanji: '徳永羚海',
    kana: 'とくなが れみ',
    hangul: '토쿠нага 레미',
    romaji: 'Remi Tokunaga',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2019-10-14',
    birthDate: '2006-10-01',
    code: 'tokunaga_remi',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/tokunaga_remi' },
      { type: 'x', url: 'https://x.com/48_RemiTokunaga' },
    ],
  },
  {
    kanji: '坂川陽香',
    kana: 'さかがわ ひゆか',
    hangul: '사카가와 히유카',
    romaji: 'Hiyuka Sakagawa',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2019-12-28',
    birthDate: '2006-10-07',
    code: 'sakagawa_hiyuka',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/sakagawa_hiyuka' },
      { type: 'x', url: 'https://x.com/Hiyuka_1007' },
    ],
  },
  {
    kanji: '長友彩海',
    kana: 'ながとも あやみ',
    hangul: '나가토모 아야미',
    romaji: 'Ayami Nagatomo',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2016-12-08',
    birthDate: '2000-11-02',
    code: 'nagatomo_ayami',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/nagatomo_ayami' },
      { type: 'x', url: 'https://x.com/ayamin_112' },
    ],
  },
  {
    kanji: '武藤小麟',
    kana: 'むとう おりん',
    hangul: '무토 오린',
    romaji: 'Orin Muto',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2016-12-08',
    birthDate: '2000-07-22',
    code: 'muto_orin',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/muto_orin' },
      { type: 'x', url: 'https://x.com/muto_orin' },
    ],
  },
  {
    kanji: '秋山由奈',
    kana: 'あきやま ゆな',
    hangul: '아키야마 유나',
    romaji: 'Yuna Akiyama',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2023-04-09',
    birthDate: '2005-12-12',
    code: 'akiyama_yuna',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/akiyama_yuna' },
      { type: 'x', url: 'https://x.com/yunachan_akb48' },
    ],
  },
  {
    kanji: '新井彩永',
    kana: 'あらい さえ',
    hangul: '아라이 사에',
    romaji: 'Sae Arai',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2023-04-09',
    birthDate: '2005-10-05',
    code: 'arai_sae',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/arai_sae' },
      { type: 'x', url: 'https://x.com/saechan_akb48' },
    ],
  },
  {
    kanji: '伊藤百花',
    kana: 'いとう ももか',
    hangul: '이토 모모카',
    romaji: 'Momoka Ito',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2024-03-17',
    birthDate: '2003-12-06',
    code: 'ito_momoka',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/ito_momoka' },
      { type: 'x', url: 'https://x.com/momoka_ito1206' },
    ],
  },

  // ==================== [2] SKE48 ====================
  {
    kanji: '熊崎晴香',
    kana: 'くまざき はるか',
    hangul: '쿠마자키 하루카',
    romaji: 'Haruka Kumazaki',
    groupId: 'ske48',
    genId: 'ske-g-active',
    status: 'active',
    joinedOn: '2012-10-06',
    birthDate: '1997-08-10',
    code: 'kumazaki_haruka',
    sns: [
      { type: 'official_profile', url: 'https://ske48.co.jp/profile/detail/kumazaki_haruka' },
      { type: 'x', url: 'https://x.com/kumachan9810' },
      { type: 'instagram', url: 'https://www.instagram.com/kumachan9810/' },
    ],
  },
  {
    kanji: '野村実代',
    kana: 'のむら みよ',
    hangul: '노무라 미요',
    romaji: 'Miyo Nomura',
    groupId: 'ske48',
    genId: 'ske-g-active',
    status: 'active',
    joinedOn: '2016-10-29',
    birthDate: '2003-02-01',
    code: 'nomura_miyo',
    sns: [
      { type: 'official_profile', url: 'https://ske48.co.jp/profile/detail/nomura_miyo' },
      { type: 'x', url: 'https://x.com/MIYOMARUKO' },
      { type: 'instagram', url: 'https://www.instagram.com/miyomaruko_0201/' },
    ],
  },
  {
    kanji: '浅井裕華',
    kana: 'あさい ゆうか',
    hangul: '아사이 유우카',
    romaji: 'Yuka Asai',
    groupId: 'ske48',
    genId: 'ske-g-active',
    status: 'active',
    joinedOn: '2015-03-15',
    birthDate: '2003-11-10',
    code: 'asai_yuka',
    sns: [
      { type: 'official_profile', url: 'https://ske48.co.jp/profile/detail/asai_yuka' },
      { type: 'x', url: 'https://x.com/ske48_yuka' },
    ],
  },
  {
    kanji: '井上瑠夏',
    kana: 'いのうえ るか',
    hangul: '이노우에 루카',
    romaji: 'Ruka Inoue',
    groupId: 'ske48',
    genId: 'ske-g-active',
    status: 'active',
    joinedOn: '2016-11-19',
    birthDate: '2001-06-12',
    code: 'inoue_ruka',
    sns: [
      { type: 'official_profile', url: 'https://ske48.co.jp/profile/detail/inoue_ruka' },
      { type: 'x', url: 'https://x.com/Inoueruka_48' },
    ],
  },
  {
    kanji: '北川愛乃',
    kana: 'きたがわ よしの',
    hangul: '키타가와 요시노',
    romaji: 'Yoshino Kitagawa',
    groupId: 'ske48',
    genId: 'ske-g-active',
    status: 'active',
    joinedOn: '2016-11-19',
    birthDate: '2001-01-24',
    code: 'kitagawa_yoshino',
    sns: [
      { type: 'official_profile', url: 'https://ske48.co.jp/profile/detail/kitagawa_yoshino' },
      { type: 'x', url: 'https://x.com/kitagawa_yosino' },
    ],
  },
  {
    kanji: '佐藤佳穂',
    kana: 'さとう かほ',
    hangul: '사토 카호',
    romaji: 'Kaho Sato',
    groupId: 'ske48',
    genId: 'ske-g-active',
    status: 'active',
    joinedOn: '2016-11-19',
    birthDate: '1997-05-16',
    code: 'sato_kaho',
    sns: [
      { type: 'official_profile', url: 'https://ske48.co.jp/profile/detail/sato_kaho' },
      { type: 'x', url: 'https://x.com/BCNOkaho' },
    ],
  },

  // ==================== [3] HKT48 ====================
  {
    kanji: '豊永阿紀',
    kana: 'とよなが あき',
    hangul: '토요нага 아키',
    romaji: 'Aki Toyonaga',
    groupId: 'hkt48',
    genId: 'hkt-g-active',
    status: 'active',
    joinedOn: '2016-07-12',
    birthDate: '1999-10-25',
    code: 'toyonaga_aki',
    sns: [
      { type: 'official_profile', url: 'https://www.hkt48.jp/profile/toyonaga_aki' },
      { type: 'x', url: 'https://x.com/aki_toyonaga' },
      { type: 'instagram', url: 'https://www.instagram.com/aki_t_official/' },
    ],
  },
  {
    kanji: '石橋颯',
    kana: 'いしばし いぶき',
    hangul: '이시바시 이부키',
    romaji: 'Ibuki Ishibashi',
    groupId: 'hkt48',
    genId: 'hkt-g-active',
    status: 'active',
    joinedOn: '2018-11-26',
    birthDate: '2005-07-22',
    code: 'ishibashi_ibuki',
    sns: [
      { type: 'official_profile', url: 'https://www.hkt48.jp/profile/ishibashi_ibuki' },
      { type: 'x', url: 'https://x.com/ibuki1484_hkt' },
      { type: 'instagram', url: 'https://www.instagram.com/ibuki_hkt48/' },
    ],
  },
  {
    kanji: '竹本くるみ',
    kana: 'たけもと くるみ',
    hangul: '타케모토 쿠루미',
    romaji: 'Kurumi Takemoto',
    groupId: 'hkt48',
    genId: 'hkt-g-active',
    status: 'active',
    joinedOn: '2018-11-26',
    birthDate: '2004-02-22',
    code: 'takemoto_kurumi',
    sns: [
      { type: 'official_profile', url: 'https://www.hkt48.jp/profile/takemoto_kurumi' },
      { type: 'x', url: 'https://x.com/kuru2_official' },
      { type: 'instagram', url: 'https://www.instagram.com/kurumi_takemoto/' },
    ],
  },
  {
    kanji: '市村愛里',
    kana: 'いちむら あいり',
    hangul: '이치무라 아이리',
    romaji: 'Airi Ichimura',
    groupId: 'hkt48',
    genId: 'hkt-g-active',
    status: 'active',
    joinedOn: '2018-11-26',
    birthDate: '2001-02-13',
    code: 'ichimura_airi',
    sns: [
      { type: 'official_profile', url: 'https://www.hkt48.jp/profile/ichimura_airi' },
      { type: 'x', url: 'https://x.com/airi_213_hkt48' },
    ],
  },
  {
    kanji: '栗原紗英',
    kana: 'くりはら さえ',
    hangul: '쿠리하라 사에',
    romaji: 'Sae Kurihara',
    groupId: 'hkt48',
    genId: 'hkt-g-active',
    status: 'active',
    joinedOn: '2013-08-04',
    birthDate: '1996-06-20',
    code: 'kurihara_sae',
    sns: [
      { type: 'official_profile', url: 'https://www.hkt48.jp/profile/kurihara_sae' },
      { type: 'x', url: 'https://x.com/38sae_kurihara' },
    ],
  },

  // ==================== [4] NGT48 ====================
  {
    kanji: '西潟茉莉奈',
    kana: 'にしがた まりな',
    hangul: '니시가타 마리나',
    romaji: 'Marina Nishigata',
    groupId: 'ngt48',
    genId: 'ngt-g-active',
    status: 'active',
    joinedOn: '2015-05-10',
    birthDate: '1995-10-16',
    code: 'nishigata_marina',
    sns: [
      { type: 'official_profile', url: 'https://ngt48.jp/profile/detail/nishigata_marina' },
      { type: 'x', url: 'https://x.com/marina_ngt48n' },
      { type: 'instagram', url: 'https://www.instagram.com/marina_nishigata/' },
    ],
  },
  {
    kanji: '清司麗菜',
    kana: 'せいじ れいな',
    hangul: '세이지 레이나',
    romaji: 'Reina Seiji',
    groupId: 'ngt48',
    genId: 'ngt-g-active',
    status: 'active',
    joinedOn: '2015-05-10',
    birthDate: '2001-04-19',
    code: 'seiji_reina',
    sns: [
      { type: 'official_profile', url: 'https://ngt48.jp/profile/detail/seiji_reina' },
      { type: 'x', url: 'https://x.com/official_seiji' },
    ],
  },
  {
    kanji: '佐藤海里',
    kana: 'さとう かいり',
    hangul: '사토 카이리',
    romaji: 'Kairi Sato',
    groupId: 'ngt48',
    genId: 'ngt-g-active',
    status: 'active',
    joinedOn: '2018-01-21',
    birthDate: '2000-08-05',
    code: 'sato_kairi',
    sns: [
      { type: 'official_profile', url: 'https://ngt48.jp/profile/detail/sato_kairi' },
      { type: 'x', url: 'https://x.com/SatouKairi_48' },
    ],
  },
  {
    kanji: '大塚七海',
    kana: 'おおつか ななみ',
    hangul: '오오츠카 나나미',
    romaji: 'Nanami Otsuka',
    groupId: 'ngt48',
    genId: 'ngt-g-active',
    status: 'active',
    joinedOn: '2018-06-12',
    birthDate: '2000-11-07',
    code: 'otsuka_nanami',
    sns: [
      { type: 'official_profile', url: 'https://ngt48.jp/profile/detail/otsuka_nanami' },
      { type: 'x', url: 'https://x.com/otsuka_nanami' },
    ],
  },
  {
    kanji: '北村優羽',
    kana: 'きたむら ゆうは',
    hangul: '키타무라 유우하',
    romaji: 'Yuha Kitamura',
    groupId: 'ngt48',
    genId: 'ngt-g-active',
    status: 'active',
    joinedOn: '2022-06-01',
    birthDate: '2004-09-22',
    code: 'kitamura_yuha',
    sns: [
      { type: 'official_profile', url: 'https://ngt48.jp/profile/detail/kitamura_yuha' },
      { type: 'x', url: 'https://x.com/yuha_kitamura' },
    ],
  },

  // ==================== [5] STU48 ====================
  {
    kanji: '岡田あずみ',
    kana: 'おかだ あずみ',
    hangul: '오카다 아즈미',
    romaji: 'Azumi Okada',
    groupId: 'stu48',
    genId: 'stu-g-active',
    status: 'active',
    joinedOn: '2022-05-03',
    birthDate: '2003-01-20',
    code: 'okada_azumi',
    sns: [
      { type: 'official_profile', url: 'https://sp.stu48.com/feature/profile_okada_azumi' },
      { type: 'x', url: 'https://x.com/azumi_stu48' },
    ],
  },
  {
    kanji: '中村舞',
    kana: 'なかむら まい',
    hangul: '나카무라 마이',
    romaji: 'Mai Nakamura',
    groupId: 'stu48',
    genId: 'stu-g-active',
    status: 'active',
    joinedOn: '2018-01-21',
    birthDate: '1999-04-04',
    code: 'nakamura_mai',
    sns: [
      { type: 'official_profile', url: 'https://sp.stu48.com/feature/profile_nakamura_mai' },
      { type: 'x', url: 'https://x.com/stu48_question' },
      { type: 'instagram', url: 'https://www.instagram.com/stu48.nakamuramai/' },
    ],
  },
  {
    kanji: '石田千穂',
    kana: 'いしだ ちほ',
    hangul: '이시다 치호',
    romaji: 'Chiho Ishida',
    groupId: 'stu48',
    genId: 'stu-g-active',
    status: 'active',
    joinedOn: '2017-03-31',
    birthDate: '2002-03-17',
    code: 'ishida_chiho',
    sns: [
      { type: 'official_profile', url: 'https://sp.stu48.com/feature/profile_ishida_chiho' },
      { type: 'x', url: 'https://x.com/_ishida_chiho' },
      { type: 'instagram', url: 'https://www.instagram.com/chiho_ishida/' },
    ],
  },

  // ==================== [6] NMB48 ====================
  {
    kanji: '小嶋花梨',
    kana: 'こじま かりん',
    hangul: '코지마 카린',
    romaji: 'Karin Kojima',
    groupId: 'nmb48',
    genId: 'nmb-g-active',
    status: 'active',
    joinedOn: '2016-06-28',
    birthDate: '1999-07-16',
    code: 'kojima_karin',
    imageUrl: 'https://sp.stu48.com/static/stu48/fansite/common/2021/logo--official.svg',
    sns: [
      { type: 'official_profile', url: 'https://www.nmb48.com/member/kojima_karin' },
      { type: 'x', url: 'https://x.com/nmb_KOJIMA_48' },
      { type: 'instagram', url: 'https://www.instagram.com/nmb_kojima_48/' },
      { type: 'youtube', url: 'https://www.youtube.com/c/kojimarin' },
    ],
  },
  {
    kanji: '塩月希依音',
    kana: 'しおつき けいと',
    hangul: '시오츠키 케이트',
    romaji: 'Keito Shiotsuki',
    groupId: 'nmb48',
    genId: 'nmb-g-active',
    status: 'active',
    joinedOn: '2018-01-21',
    birthDate: '2005-12-15',
    code: 'shiotsuki_keito',
    imageUrl: 'https://sp.stu48.com/static/stu48/fansite/common/2021/logo--official.svg',
    sns: [
      { type: 'official_profile', url: 'https://www.nmb48.com/member/shiotsuki_keito' },
      { type: 'x', url: 'https://x.com/keity_1215' },
      { type: 'instagram', url: 'https://www.instagram.com/keity_1215/' },
    ],
  },
  {
    kanji: '坂田心咲',
    kana: 'さかた みさき',
    hangul: '사카타 미사키',
    romaji: 'Misaki Sakata',
    groupId: 'nmb48',
    genId: 'nmb-g-active',
    status: 'active',
    joinedOn: '2022-01-01',
    birthDate: '2005-11-08',
    code: 'sakata_misaki',
    imageUrl: 'https://sp.stu48.com/static/stu48/fansite/common/2021/logo--official.svg',
    sns: [
      { type: 'official_profile', url: 'https://www.nmb48.com/member/sakata_misaki' },
      { type: 'x', url: 'https://x.com/Michapiiii_' },
      { type: 'instagram', url: 'https://www.instagram.com/michapiiii_/' },
    ],
  },

  // ==================== [7] Overseas (JKT48 / BNK48 / CGM48 / MNL48 / Team SH / Team TP / KLP48) ====================
  {
    kanji: '行天優莉奈',
    kana: 'ぎょうてん ゆりな',
    hangul: '교텐 유리나',
    romaji: 'Yurina Gyoten',
    groupId: 'klp48',
    genId: 'klp-g-active',
    status: 'active',
    joinedOn: '2014-04-03',
    birthDate: '1999-03-14',
    code: 'yurina_gyoten',
    sns: [
      { type: 'official_profile', url: 'https://klp48.my/members/yurina_gyoten' },
      { type: 'x', url: 'https://x.com/tenten_yurina' },
      { type: 'instagram', url: 'https://www.instagram.com/yurina.gyoten/' },
    ],
  },
  {
    kanji: '黒須遥香',
    kana: 'くろす はるか',
    hangul: '쿠로스 하루카',
    romaji: 'Haruka Kurosu',
    groupId: 'klp48',
    genId: 'klp-g-active',
    status: 'active',
    joinedOn: '2016-12-08',
    birthDate: '2001-02-28',
    code: 'haruka_kurosu',
    sns: [
      { type: 'official_profile', url: 'https://klp48.my/members/haruka_kurosu' },
      { type: 'x', url: 'https://x.com/kurosu_haruka_' },
      { type: 'instagram', url: 'https://www.instagram.com/kurosu_haruka/' },
    ],
  },
  {
    kanji: '山根涼羽',
    kana: 'やまね すずは',
    hangul: '야마네 스즈하',
    romaji: 'Suzuha Yamane',
    groupId: 'klp48',
    genId: 'klp-g-active',
    status: 'active',
    joinedOn: '2016-12-08',
    birthDate: '2000-08-11',
    code: 'suzuha_yamane',
    sns: [
      { type: 'official_profile', url: 'https://klp48.my/members/suzuha_yamane' },
      { type: 'x', url: 'https://x.com/48_asayan' },
      { type: 'instagram', url: 'https://www.instagram.com/suzunya_48/' },
    ],
  },
];

export function getAKB48GroupMembers(): Member[] {
  return AKB48G_SEEDS.map((seed) => {
    const id = toSlug(seed.groupId, seed.kana);
    const romajiName = seed.romaji || formatPersonRomaji(seed.kana);
    const hangulName = seed.hangul || kanaToHangul(seed.kana);
    const avatar = generateAvatar(id, seed.kanji);

    const lookupKey = `${seed.groupId}_${seed.kanji.replace(/\s+/g, '')}`;
    const resolvedImage =
      VERIFIED_OFFICIAL_MAP[lookupKey] ||
      SCRAPED_IMAGES[lookupKey] ||
      seed.imageUrl ||
      null;

    const links: MemberLink[] = (seed.sns || []).map((s) => ({
      type: s.type,
      url: s.url,
      label: null,
      isOfficial: true,
      status: 'ok',
      lastCheckedAt: '2026-08-16',
      lastStatusCode: 200,
    }));

    return {
      id,
      name: {
        ja: {
          kanji: seed.kanji,
          kana: seed.kana,
        },
        ko: {
          hangul: hangulName,
        },
        en: {
          romaji: romajiName,
        },
        aliases: [romajiName.toLowerCase(), seed.kanji, hangulName],
      },
      primaryGroupId: seed.groupId,
      primaryGenerationId: seed.genId,
      status: seed.status || 'active',
      memberships: [
        {
          groupId: seed.groupId,
          generationId: seed.genId,
          joinedOn: seed.joinedOn,
          leftOn: seed.leftOn ?? null,
          isConcurrent: false,
          endReason: seed.status === 'graduated' ? 'graduation' : null,
        },
      ],
      birthDate: seed.birthDate || null,
      birthplace: null,
      officialCode: seed.code || null,
      imageUrl: resolvedImage,
      links,
      avatar,
      provenance: {
        source: 'official',
        sourceUrl: seed.sns?.[0]?.url || 'https://www.akb48.co.jp/',
        checkedAt: '2026-08-16',
        note: 'AKB48 Group verified dataset from official sites',
      },
    };
  });
}
