import { kanaToHepburn, formatPersonRomaji, toSlug } from '../lib/romaji';
import { kanaToHangul } from '../lib/hangul';
import { generateAvatar } from '../lib/avatar';
import type { Member, MemberLink, LinkType } from '../../src/lib/schema';

interface AKBMemberSeed {
  kanji: string;
  kana: string;
  hangul?: string;
  romaji?: string;
  groupId: string;
  genId: string;
  status?: 'active' | 'graduated';
  joinedOn: string;
  leftOn?: string | null;
  birthDate?: string;
  code?: string;
  imageUrl?: string | null;
  sns?: { type: LinkType; url: string }[];
}

const AKB48G_SEEDS: AKBMemberSeed[] = [
  // ==================== [1] AKB48 (Verified Official CloudFront CDN 1:1 mapping) ====================
  {
    kanji: '小栗有以',
    kana: 'おぐり ゆい',
    hangul: '오구리 유이',
    romaji: 'Yui Oguri',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2014-04-03',
    birthDate: '2001-12-26',
    code: 'oguri_yui',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100816.jpg',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/oguri_yui' },
      { type: 'x', url: 'https://x.com/yuiyui_maromaro' },
      { type: 'instagram', url: 'https://www.instagram.com/yuioguri_1226/' },
    ],
  },
  {
    kanji: '倉野尾成美',
    kana: 'くらのお なるみ',
    hangul: '쿠라노오 나루미',
    romaji: 'Narumi Kuranoo',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2014-04-03',
    birthDate: '2000-11-08',
    code: 'kuranoo_narumi',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100846.jpg',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/kuranoo_narumi' },
      { type: 'x', url: 'https://x.com/Kuranoo_Narumi_' },
      { type: 'instagram', url: 'https://www.instagram.com/noochan_1108/' },
    ],
  },
  {
    kanji: '千葉恵里',
    kana: 'ちば えりい',
    hangul: '치바 에리이',
    romaji: 'Erii Chiba',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2015-05-10',
    birthDate: '2003-10-27',
    code: 'chiba_erii',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100927.jpg',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/chiba_erii' },
      { type: 'x', url: 'https://x.com/erii_20031027' },
      { type: 'instagram', url: 'https://www.instagram.com/eriierii_1027/' },
    ],
  },
  {
    kanji: '山内瑞葵',
    kana: 'やまうち みずき',
    hangul: '야마우치 미즈키',
    romaji: 'Mizuki Yamauchi',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2016-12-08',
    birthDate: '2001-09-20',
    code: 'yamauchi_mizuki',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100951.jpg',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/yamauchi_mizuki' },
      { type: 'x', url: 'https://x.com/MizukiYamauchi' },
      { type: 'instagram', url: 'https://www.instagram.com/zukky_48/' },
    ],
  },
  {
    kanji: '佐藤綺星',
    kana: 'さとう あいり',
    hangul: '사토 아이리',
    romaji: 'Airi Sato',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2022-05-04',
    birthDate: '2004-06-24',
    code: 'sato_airi',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83101000.jpg',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/sato_airi' },
      { type: 'x', url: 'https://x.com/airi_sato0624' },
      { type: 'instagram', url: 'https://www.instagram.com/airi_sato0624/' },
    ],
  },
  {
    kanji: '八木愛月',
    kana: 'やぎ あづき',
    hangul: '야기 아즈키',
    romaji: 'Azuki Yagi',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2023-04-09',
    birthDate: '2005-03-22',
    code: 'yagi_azuki',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101015.jpg',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/yagi_azuki' },
      { type: 'x', url: 'https://x.com/azuki_yagi0322' },
    ],
  },
  {
    kanji: '岩立沙穂',
    kana: 'いわたて さほ',
    hangul: '이와타테 사호',
    romaji: 'Saho Iwatate',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2011-12-08',
    birthDate: '1994-10-04',
    code: 'iwatate_saho',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100622.jpg',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/iwatate_saho' },
      { type: 'x', url: 'https://x.com/yahho_sahho' },
      { type: 'instagram', url: 'https://www.instagram.com/saho_iwatate104/' },
    ],
  },
  {
    kanji: '福岡聖菜',
    kana: 'ふくおか せいな',
    hangul: '후쿠오카 세이나',
    romaji: 'Seina Fukuoka',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2013-06-05',
    birthDate: '2000-08-01',
    code: 'fukuoka_seina',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100790.jpg',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/fukuoka_seina' },
      { type: 'x', url: 'https://x.com/seina_fuku48' },
      { type: 'instagram', url: 'https://www.instagram.com/seina___fuku48/' },
    ],
  },
  {
    kanji: '下尾みう',
    kana: 'したお みう',
    hangul: '시타오 미우',
    romaji: 'Miu Shitao',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2014-04-03',
    birthDate: '2001-04-03',
    code: 'shitao_miu',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100838.jpg',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/shitao_miu' },
      { type: 'x', url: 'https://x.com/miumiu_0403' },
      { type: 'instagram', url: 'https://www.instagram.com/miumiu1343/' },
    ],
  },
  {
    kanji: '髙橋彩音',
    kana: 'たかはし あやね',
    hangul: '타카하시 아야네',
    romaji: 'Ayane Takahashi',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2014-04-03',
    birthDate: '1997-12-30',
    code: 'takahashi_ayane',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100814.jpg',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/takahashi_ayane' },
      { type: 'x', url: 'https://x.com/aya__takahashi' },
    ],
  },
  {
    kanji: '永野芹佳',
    kana: 'ながの せりか',
    hangul: '나가노 세리카',
    romaji: 'Serika Nagano',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2014-04-03',
    birthDate: '2001-03-27',
    code: 'nagano_serika',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100828.jpg',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/nagano_serika' },
      { type: 'x', url: 'https://x.com/akb48serika' },
    ],
  },
  {
    kanji: '橋本陽菜',
    kana: 'はしもと はるな',
    hangul: '하시모토 하루나',
    romaji: 'Haruna Hashimoto',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2014-04-03',
    birthDate: '2000-05-25',
    code: 'hashimoto_haruna',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100824.jpg',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/hashimoto_haruna' },
      { type: 'x', url: 'https://x.com/harupyon_0525' },
    ],
  },
  {
    kanji: '徳永羚海',
    kana: 'とくなが れみ',
    hangul: '토쿠나가 레미',
    romaji: 'Remi Tokunaga',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2019-10-14',
    birthDate: '2006-10-01',
    code: 'tokunaga_remi',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100993.jpg',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/tokunaga_remi' },
      { type: 'x', url: 'https://x.com/48_RemiTokunaga' },
    ],
  },
  {
    kanji: '坂川陽香',
    kana: 'さかがわ ひゆか',
    hangul: '사카가와 히유카',
    romaji: 'Hiyuka Sakagawa',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2019-12-28',
    birthDate: '2006-10-07',
    code: 'sakagawa_hiyuka',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100997.jpg',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/sakagawa_hiyuka' },
      { type: 'x', url: 'https://x.com/Hiyuka_1007' },
    ],
  },
  {
    kanji: '長友彩海',
    kana: 'ながとも あやみ',
    hangul: '나가토모 아야미',
    romaji: 'Ayami Nagatomo',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2016-12-08',
    birthDate: '2000-11-02',
    code: 'nagatomo_ayami',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100943.jpg',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/nagatomo_ayami' },
      { type: 'x', url: 'https://x.com/ayamin_112' },
    ],
  },
  {
    kanji: '武藤小麟',
    kana: 'むとう おりん',
    hangul: '무토 오린',
    romaji: 'Orin Muto',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2016-12-08',
    birthDate: '2000-07-22',
    code: 'muto_orin',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100949.jpg',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/muto_orin' },
      { type: 'x', url: 'https://x.com/muto_orin' },
    ],
  },
  {
    kanji: '秋山由奈',
    kana: 'あきやま ゆな',
    hangul: '아키야마 유나',
    romaji: 'Yuna Akiyama',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2023-04-09',
    birthDate: '2005-12-12',
    code: 'akiyama_yuna',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101009.jpg',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/akiyama_yuna' },
      { type: 'x', url: 'https://x.com/yunachan_akb48' },
    ],
  },
  {
    kanji: '新井彩永',
    kana: 'あらい さえ',
    hangul: '아라이 사에',
    romaji: 'Sae Arai',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2023-04-09',
    birthDate: '2005-10-05',
    code: 'arai_sae',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101010.jpg',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/arai_sae' },
      { type: 'x', url: 'https://x.com/saechan_akb48' },
    ],
  },
  {
    kanji: '伊藤百花',
    kana: 'いとう ももか',
    hangul: '이토 모모카',
    romaji: 'Momoka Ito',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2024-03-17',
    birthDate: '2003-12-06',
    code: 'ito_momoka',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/hashiranokai/member/83101017.jpg',
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/ito_momoka' },
      { type: 'x', url: 'https://x.com/momoka_ito1206' },
    ],
  },
  {
    kanji: '向井地美音',
    kana: 'むかいち みおん',
    hangul: '무카이치 미온',
    romaji: 'Mion Mukaichi',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2013-06-05',
    birthDate: '1998-01-29',
    code: 'mukaichi_mion',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/mukaichi_mion' },
      { type: 'x', url: 'https://x.com/mionnn_48' },
      { type: 'instagram', url: 'https://www.instagram.com/__mion.m__/' },
    ],
  },
  {
    kanji: '村山彩希',
    kana: 'むらやま ゆいり',
    hangul: '무라야마 유이리',
    romaji: 'Yuiri Murayama',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'active',
    joinedOn: '2011-12-08',
    birthDate: '1997-06-15',
    code: 'murayama_yuiri',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://www.akb48.co.jp/about/members/detail/murayama_yuiri' },
      { type: 'x', url: 'https://x.com/yuirii_murayama' },
    ],
  },
  {
    kanji: '柏木由紀',
    kana: 'かしわぎ ゆき',
    hangul: '카시와기 유키',
    romaji: 'Yuki Kashiwagi',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'graduated',
    joinedOn: '2006-12-03',
    leftOn: '2024-04-30',
    birthDate: '1991-07-15',
    imageUrl: null,
    sns: [
      { type: 'x', url: 'https://x.com/Yukiriiiin__K' },
      { type: 'instagram', url: 'https://www.instagram.com/yukikashiwagi_official/' },
      { type: 'youtube', url: 'https://www.youtube.com/c/yukirinworld' },
    ],
  },
  {
    kanji: '前田敦子',
    kana: 'まえだ あつこ',
    hangul: '마에다 아츠코',
    romaji: 'Atsuko Maeda',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'graduated',
    joinedOn: '2005-12-08',
    leftOn: '2012-08-27',
    birthDate: '1991-07-10',
    imageUrl: null,
    sns: [
      { type: 'x', url: 'https://x.com/Atsuko_100' },
      { type: 'instagram', url: 'https://www.instagram.com/atsuko_maeda_official/' },
    ],
  },
  {
    kanji: '大島優子',
    kana: 'おおしま ゆうこ',
    hangul: '오오시마 유코',
    romaji: 'Yuko Oshima',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'graduated',
    joinedOn: '2006-02-26',
    leftOn: '2014-06-09',
    birthDate: '1988-10-17',
    imageUrl: null,
    sns: [
      { type: 'x', url: 'https://x.com/Oshima__Yuko' },
      { type: 'instagram', url: 'https://www.instagram.com/yuk00shima/' },
    ],
  },
  {
    kanji: '指原莉乃',
    kana: 'さしはら りの',
    hangul: '사시하라 리노',
    romaji: 'Rino Sashihara',
    groupId: 'akb48',
    genId: 'akb-g-active',
    status: 'graduated',
    joinedOn: '2007-10-06',
    leftOn: '2019-04-28',
    birthDate: '1992-11-21',
    imageUrl: null,
    sns: [
      { type: 'x', url: 'https://x.com/345__chan' },
      { type: 'instagram', url: 'https://www.instagram.com/345insta/' },
      { type: 'youtube', url: 'https://www.youtube.com/c/345channel' },
    ],
  },

  // ==================== [2] SKE48 ====================
  {
    kanji: '熊崎晴香',
    kana: 'くまざき はるか',
    hangul: '쿠마자키 하루카',
    romaji: 'Haruka Kumazaki',
    groupId: 'ske48',
    genId: 'ske-g-active',
    status: 'active',
    joinedOn: '2012-10-06',
    birthDate: '1997-08-10',
    code: 'kumazaki_haruka',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://ske48.co.jp/profile/detail/kumazaki_haruka' },
      { type: 'x', url: 'https://x.com/kumachan9810' },
      { type: 'instagram', url: 'https://www.instagram.com/kumachan9810/' },
    ],
  },
  {
    kanji: '末永桜花',
    kana: 'すえなが おうか',
    hangul: '수에나가 오우카',
    romaji: 'Ouka Suenaga',
    groupId: 'ske48',
    genId: 'ske-g-active',
    status: 'active',
    joinedOn: '2015-03-15',
    birthDate: '2002-02-26',
    code: 'suenaga_ouka',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://ske48.co.jp/profile/detail/suenaga_ouka' },
      { type: 'x', url: 'https://x.com/Ouka_ske0226' },
      { type: 'instagram', url: 'https://www.instagram.com/ouka_ske0226/' },
    ],
  },
  {
    kanji: '野村実代',
    kana: 'のむら みよ',
    hangul: '노무라 미요',
    romaji: 'Miyo Nomura',
    groupId: 'ske48',
    genId: 'ske-g-active',
    status: 'active',
    joinedOn: '2016-10-29',
    birthDate: '2003-02-01',
    code: 'nomura_miyo',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://ske48.co.jp/profile/detail/nomura_miyo' },
      { type: 'x', url: 'https://x.com/MIYOMARUKO' },
      { type: 'instagram', url: 'https://www.instagram.com/miyomaruko_0201/' },
    ],
  },
  {
    kanji: '松井珠理奈',
    kana: 'まつい じゅりな',
    hangul: '마츠이 쥬리나',
    romaji: 'Jurina Matsui',
    groupId: 'ske48',
    genId: 'ske-g-active',
    status: 'graduated',
    joinedOn: '2008-08-23',
    leftOn: '2021-04-30',
    birthDate: '1997-03-08',
    imageUrl: null,
    sns: [
      { type: 'x', url: 'https://x.com/JURINA38G' },
      { type: 'instagram', url: 'https://www.instagram.com/jurinamatsui3/' },
    ],
  },

  // ==================== [3] NMB48 ====================
  {
    kanji: '小嶋花梨',
    kana: 'こじま かりん',
    hangul: '코지마 카린',
    romaji: 'Karin Kojima',
    groupId: 'nmb48',
    genId: 'nmb-g-active',
    status: 'active',
    joinedOn: '2016-06-28',
    birthDate: '1999-07-16',
    code: 'kojima_karin',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://www.nmb48.com/member/kojima_karin' },
      { type: 'x', url: 'https://x.com/nmb_KOJIMA_48' },
      { type: 'instagram', url: 'https://www.instagram.com/nmb_kojima_48/' },
      { type: 'youtube', url: 'https://www.youtube.com/c/kojimarin' },
    ],
  },
  {
    kanji: '塩月希依音',
    kana: 'しおつき けいと',
    hangul: '시오츠키 케이트',
    romaji: 'Keito Shiotsuki',
    groupId: 'nmb48',
    genId: 'nmb-g-active',
    status: 'active',
    joinedOn: '2018-01-21',
    birthDate: '2005-12-15',
    code: 'shiotsuki_keito',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://www.nmb48.com/member/shiotsuki_keito' },
      { type: 'x', url: 'https://x.com/keity_1215' },
      { type: 'instagram', url: 'https://www.instagram.com/keity_1215/' },
    ],
  },
  {
    kanji: '坂田心咲',
    kana: 'さかた みさき',
    hangul: '사카타 미사키',
    romaji: 'Misaki Sakata',
    groupId: 'nmb48',
    genId: 'nmb-g-active',
    status: 'active',
    joinedOn: '2022-01-01',
    birthDate: '2005-11-08',
    code: 'sakata_misaki',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://www.nmb48.com/member/sakata_misaki' },
      { type: 'x', url: 'https://x.com/Michapiiii_' },
      { type: 'instagram', url: 'https://www.instagram.com/michapiiii_/' },
    ],
  },
  {
    kanji: '山本彩',
    kana: 'やまもと さやか',
    hangul: '야마모토 사야카',
    romaji: 'Sayaka Yamamoto',
    groupId: 'nmb48',
    genId: 'nmb-g-active',
    status: 'graduated',
    joinedOn: '2010-10-09',
    leftOn: '2018-11-04',
    birthDate: '1993-07-14',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://yamamotosayaka.jp/' },
      { type: 'x', url: 'https://x.com/SayakaNeon' },
      { type: 'instagram', url: 'https://www.instagram.com/sayaka__714/' },
      { type: 'youtube', url: 'https://www.youtube.com/c/sayakayamamoto' },
    ],
  },

  // ==================== [4] HKT48 ====================
  {
    kanji: '豊永阿紀',
    kana: 'とよなが あき',
    hangul: '토요нага 아키',
    romaji: 'Aki Toyonaga',
    groupId: 'hkt48',
    genId: 'hkt-g-active',
    status: 'active',
    joinedOn: '2016-07-12',
    birthDate: '1999-10-25',
    code: 'toyonaga_aki',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://www.hkt48.jp/profile/toyonaga_aki' },
      { type: 'x', url: 'https://x.com/aki_toyonaga' },
      { type: 'instagram', url: 'https://www.instagram.com/aki_t_official/' },
    ],
  },
  {
    kanji: '石橋颯',
    kana: 'いしばし いぶき',
    hangul: '이시바시 이부키',
    romaji: 'Ibuki Ishibashi',
    groupId: 'hkt48',
    genId: 'hkt-g-active',
    status: 'active',
    joinedOn: '2018-11-26',
    birthDate: '2005-07-22',
    code: 'ishibashi_ibuki',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://www.hkt48.jp/profile/ishibashi_ibuki' },
      { type: 'x', url: 'https://x.com/ibuki1484_hkt' },
      { type: 'instagram', url: 'https://www.instagram.com/ibuki_hkt48/' },
    ],
  },
  {
    kanji: '竹本くるみ',
    kana: 'たけもと くるみ',
    hangul: '타케모토 쿠루미',
    romaji: 'Kurumi Takemoto',
    groupId: 'hkt48',
    genId: 'hkt-g-active',
    status: 'active',
    joinedOn: '2018-11-26',
    birthDate: '2004-02-22',
    code: 'takemoto_kurumi',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://www.hkt48.jp/profile/takemoto_kurumi' },
      { type: 'x', url: 'https://x.com/kuru2_official' },
      { type: 'instagram', url: 'https://www.instagram.com/kurumi_takemoto/' },
    ],
  },
  {
    kanji: '宮脇咲良',
    kana: 'みやわき さくら',
    hangul: '미야와키 사쿠라',
    romaji: 'Sakura Miyawaki',
    groupId: 'hkt48',
    genId: 'hkt-g-active',
    status: 'graduated',
    joinedOn: '2011-10-23',
    leftOn: '2021-06-19',
    birthDate: '1998-03-19',
    imageUrl: null,
    sns: [
      { type: 'x', url: 'https://x.com/39saku_chan' },
      { type: 'instagram', url: 'https://www.instagram.com/39saku_chan/' },
      { type: 'youtube', url: 'https://www.youtube.com/channel/UC9Z0cgzpLK2DC4Um9VOQK5Q' },
    ],
  },

  // ==================== [5] NGT48 ====================
  {
    kanji: '藤崎未夢',
    kana: 'ふじさき みゆ',
    hangul: '후지사키 미유',
    romaji: 'Miyu Fujisaki',
    groupId: 'ngt48',
    genId: 'ngt-g-active',
    status: 'active',
    joinedOn: '2018-01-21',
    birthDate: '2000-11-17',
    code: 'fujisaki_miyu',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://ngt48.jp/profile/detail/fujisaki_miyu' },
      { type: 'x', url: 'https://x.com/miyu_miyu_ngt48' },
      { type: 'instagram', url: 'https://www.instagram.com/miyu_miyu_fujisaki/' },
    ],
  },
  {
    kanji: '西潟茉莉奈',
    kana: 'にしがた まりな',
    hangul: '니시가타 마리나',
    romaji: 'Marina Nishigata',
    groupId: 'ngt48',
    genId: 'ngt-g-active',
    status: 'active',
    joinedOn: '2015-05-10',
    birthDate: '1995-10-16',
    code: 'nishigata_marina',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://ngt48.jp/profile/detail/nishigata_marina' },
      { type: 'x', url: 'https://x.com/marina_ngt48n' },
      { type: 'instagram', url: 'https://www.instagram.com/marina_nishigata/' },
    ],
  },
  {
    kanji: '本間日陽',
    kana: 'ほんま ひなた',
    hangul: '혼마 히나타',
    romaji: 'Hinata Homma',
    groupId: 'ngt48',
    genId: 'ngt-g-active',
    status: 'graduated',
    joinedOn: '2015-08-21',
    leftOn: '2024-04-13',
    birthDate: '1999-11-10',
    imageUrl: null,
    sns: [
      { type: 'x', url: 'https://x.com/hinata_homma' },
      { type: 'instagram', url: 'https://www.instagram.com/hinata_homma1110/' },
    ],
  },

  // ==================== [6] STU48 ====================
  {
    kanji: '岡田あずみ',
    kana: 'おかだ あずみ',
    hangul: '오카다 아즈미',
    romaji: 'Azumi Okada',
    groupId: 'stu48',
    genId: 'stu-g-active',
    status: 'active',
    joinedOn: '2022-05-03',
    birthDate: '2003-01-20',
    code: 'okada_azumi',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://sp.stu48.com/feature/profile_okada_azumi' },
      { type: 'x', url: 'https://x.com/azumi_stu48' },
    ],
  },
  {
    kanji: '中村舞',
    kana: 'なかむら まい',
    hangul: '나카무라 마이',
    romaji: 'Mai Nakamura',
    groupId: 'stu48',
    genId: 'stu-g-active',
    status: 'active',
    joinedOn: '2018-01-21',
    birthDate: '1999-04-04',
    code: 'nakamura_mai',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://sp.stu48.com/feature/profile_nakamura_mai' },
      { type: 'x', url: 'https://x.com/stu48_question' },
      { type: 'instagram', url: 'https://www.instagram.com/stu48.nakamuramai/' },
    ],
  },
  {
    kanji: '石田千穂',
    kana: 'いしだ ちほ',
    hangul: '이시다 치호',
    romaji: 'Chiho Ishida',
    groupId: 'stu48',
    genId: 'stu-g-active',
    status: 'active',
    joinedOn: '2017-03-31',
    birthDate: '2002-03-17',
    code: 'ishida_chiho',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://sp.stu48.com/feature/profile_ishida_chiho' },
      { type: 'x', url: 'https://x.com/_ishida_chiho' },
      { type: 'instagram', url: 'https://www.instagram.com/chiho_ishida/' },
    ],
  },
  {
    kanji: '瀧野由美子',
    kana: 'たきの ゆみこ',
    hangul: '타키노 유미코',
    romaji: 'Yumiko Takino',
    groupId: 'stu48',
    genId: 'stu-g-active',
    status: 'graduated',
    joinedOn: '2017-03-31',
    leftOn: '2023-11-30',
    birthDate: '1997-09-24',
    imageUrl: null,
    sns: [
      { type: 'x', url: 'https://x.com/yumiko_takino_' },
      { type: 'instagram', url: 'https://www.instagram.com/yumiko_anko/' },
    ],
  },

  // ==================== [7] JKT48 ====================
  {
    kanji: 'シャニ',
    kana: 'しゃに',
    hangul: '샤니',
    romaji: 'Shani Indira Natio',
    groupId: 'jkt48',
    genId: 'jkt-g-active',
    status: 'active',
    joinedOn: '2014-03-15',
    birthDate: '1998-10-05',
    code: 'shani_indira_natio',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://jkt48.com/member/detail/id/shani_indira_natio' },
      { type: 'x', url: 'https://x.com/N_ShaniJKT48' },
      { type: 'instagram', url: 'https://www.instagram.com/jkt48shani/' },
    ],
  },
  {
    kanji: 'フェニ',
    kana: 'ふぇに',
    hangul: '페니',
    romaji: 'Feni Fitriyanti',
    groupId: 'jkt48',
    genId: 'jkt-g-active',
    status: 'active',
    joinedOn: '2014-03-15',
    birthDate: '1999-01-16',
    code: 'feni_fitriyanti',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://jkt48.com/member/detail/id/feni_fitriyanti' },
      { type: 'x', url: 'https://x.com/F_FeniJKT48' },
      { type: 'instagram', url: 'https://www.instagram.com/jkt48feni/' },
    ],
  },
  {
    kanji: 'フレヤ',
    kana: 'ふれや',
    hangul: '프레야',
    romaji: 'Freya Jayawardana',
    groupId: 'jkt48',
    genId: 'jkt-g-active',
    status: 'active',
    joinedOn: '2018-09-29',
    birthDate: '2006-02-13',
    code: 'freya_jayawardana',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://jkt48.com/member/detail/id/freya_jayawardana' },
      { type: 'x', url: 'https://x.com/Freya_JKT48' },
      { type: 'instagram', url: 'https://www.instagram.com/jkt48.freya/' },
    ],
  },

  // ==================== [8] BNK48 ====================
  {
    kanji: 'チャープラン',
    kana: 'ちゃーぷらん',
    hangul: '체프랑',
    romaji: 'Cherprang Areekul',
    groupId: 'bnk48',
    genId: 'bnk-g-active',
    status: 'graduated',
    joinedOn: '2017-02-12',
    leftOn: '2023-10-30',
    birthDate: '1996-05-02',
    imageUrl: null,
    sns: [
      { type: 'x', url: 'https://x.com/cherprang_areek' },
      { type: 'instagram', url: 'https://www.instagram.com/cherprang.areekul/' },
    ],
  },
  {
    kanji: 'フープ',
    kana: 'ふーぷ',
    hangul: '후프',
    romaji: 'Patalee Prasertteerachai',
    groupId: 'bnk48',
    genId: 'bnk-g-active',
    status: 'active',
    joinedOn: '2020-11-28',
    birthDate: '2002-09-18',
    code: 'hoop',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://www.bnk48.com/bnk48-members/detail/hoop' },
      { type: 'instagram', url: 'https://www.instagram.com/hoop.bnk48official/' },
    ],
  },

  // ==================== [9] CGM48 ====================
  {
    kanji: '伊豆田莉奈',
    kana: 'いずた りな',
    hangul: '이즈타 리나',
    romaji: 'Rina Izuta',
    groupId: 'cgm48',
    genId: 'cgm-g-active',
    status: 'graduated',
    joinedOn: '2010-03-31',
    leftOn: '2024-11-30',
    birthDate: '1995-11-26',
    imageUrl: null,
    sns: [
      { type: 'x', url: 'https://x.com/izurina_cgm48' },
      { type: 'instagram', url: 'https://www.instagram.com/rina.izuta.cgm48/' },
    ],
  },
  {
    kanji: 'オーム',
    kana: 'おーむ',
    hangul: '아옴',
    romaji: 'Manichar Aimdilokwong',
    groupId: 'cgm48',
    genId: 'cgm-g-active',
    status: 'active',
    joinedOn: '2019-10-26',
    birthDate: '1995-11-10',
    code: 'aom',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://cgm48official.com/members/aom' },
      { type: 'instagram', url: 'https://www.instagram.com/aom.cgm48official/' },
    ],
  },

  // ==================== [10] MNL48 ====================
  {
    kanji: 'シェキ',
    kana: 'しぇき',
    hangul: '셰키',
    romaji: 'Shekinah Arzaga',
    groupId: 'mnl48',
    genId: 'mnl-g-active',
    status: 'active',
    joinedOn: '2018-04-28',
    birthDate: '2000-07-20',
    code: 'sheki',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://mnl48.ph/members/sheki' },
      { type: 'instagram', url: 'https://www.instagram.com/sheki.mnl48official/' },
    ],
  },

  // ==================== [11] AKB48 Team SH ====================
  {
    kanji: '劉念',
    kana: 'りゅう ねん',
    hangul: '류녠',
    romaji: 'Liu Nian',
    groupId: 'akb48-team-sh',
    genId: 'sh-g-active',
    status: 'active',
    joinedOn: '2018-12-03',
    birthDate: '2001-02-02',
    code: 'liu_nian',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://www.akb48-china.com/member/liu_nian' },
      { type: 'weibo', url: 'https://weibo.com/u/6591022137' },
    ],
  },

  // ==================== [12] AKB48 Team TP ====================
  {
    kanji: '劉語晴',
    kana: 'りゅう ごせい',
    hangul: '류위칭',
    romaji: 'Liu Yu-ching',
    groupId: 'akb48-team-tp',
    genId: 'tp-g-active',
    status: 'active',
    joinedOn: '2018-08-26',
    birthDate: '1996-07-14',
    code: '77_yuqing',
    imageUrl: null,
    sns: [
      { type: 'official_profile', url: 'https://www.akb48teamtp.com/members/77_yuqing' },
      { type: 'instagram', url: 'https://www.instagram.com/yuqing__77/' },
    ],
  },

  // ==================== [13] KLP48 ====================
  {
    kanji: '行天優莉奈',
    kana: 'ぎょうてん ゆりな',
    hangul: '교텐 유리나',
    romaji: 'Yurina Gyoten',
    groupId: 'klp48',
    genId: 'klp-g-active',
    status: 'active',
    joinedOn: '2014-04-03',
    birthDate: '1999-03-14',
    code: 'yurina_gyoten',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100840.jpg',
    sns: [
      { type: 'official_profile', url: 'https://klp48.my/members/yurina_gyoten' },
      { type: 'x', url: 'https://x.com/tenten_yurina' },
      { type: 'instagram', url: 'https://www.instagram.com/yurina.gyoten/' },
    ],
  },
  {
    kanji: '黒須遥香',
    kana: 'くろす はるか',
    hangul: '쿠로스 하루카',
    romaji: 'Haruka Kurosu',
    groupId: 'klp48',
    genId: 'klp-g-active',
    status: 'active',
    joinedOn: '2016-12-08',
    birthDate: '2001-02-28',
    code: 'haruka_kurosu',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100937.jpg',
    sns: [
      { type: 'official_profile', url: 'https://klp48.my/members/haruka_kurosu' },
      { type: 'x', url: 'https://x.com/kurosu_haruka_' },
      { type: 'instagram', url: 'https://www.instagram.com/kurosu_haruka/' },
    ],
  },
  {
    kanji: '山根涼羽',
    kana: 'やまね すずは',
    hangul: '야마네 스즈하',
    romaji: 'Suzuha Yamane',
    groupId: 'klp48',
    genId: 'klp-g-active',
    status: 'active',
    joinedOn: '2016-12-08',
    birthDate: '2000-08-11',
    code: 'suzuha_yamane',
    imageUrl: 'https://d2r1lkk9i7row.cloudfront.net/mobile/member/83100952.jpg',
    sns: [
      { type: 'official_profile', url: 'https://klp48.my/members/suzuha_yamane' },
      { type: 'x', url: 'https://x.com/48_asayan' },
      { type: 'instagram', url: 'https://www.instagram.com/suzunya_48/' },
    ],
  },
];

export function getAKB48GroupMembers(): Member[] {
  return AKB48G_SEEDS.map((seed) => {
    const id = toSlug(seed.groupId, seed.kana);
    const romajiName = seed.romaji || formatPersonRomaji(seed.kana);
    const hangulName = seed.hangul || kanaToHangul(seed.kana);
    const avatar = generateAvatar(id, seed.kanji);

    const links: MemberLink[] = (seed.sns || []).map((s) => ({
      type: s.type,
      url: s.url,
      label: null,
      isOfficial: true,
      status: 'ok',
      lastCheckedAt: '2026-08-16',
      lastStatusCode: 200,
    }));

    return {
      id,
      name: {
        ja: {
          kanji: seed.kanji,
          kana: seed.kana,
        },
        ko: {
          hangul: hangulName,
        },
        en: {
          romaji: romajiName,
        },
        aliases: [romajiName.toLowerCase(), seed.kanji, hangulName],
      },
      primaryGroupId: seed.groupId,
      primaryGenerationId: seed.genId,
      status: seed.status || 'active',
      memberships: [
        {
          groupId: seed.groupId,
          generationId: seed.genId,
          joinedOn: seed.joinedOn,
          leftOn: seed.leftOn ?? null,
          isConcurrent: false,
          endReason: seed.status === 'graduated' ? 'graduation' : null,
        },
      ],
      birthDate: seed.birthDate || null,
      birthplace: null,
      officialCode: seed.code || null,
      imageUrl: seed.imageUrl || null,
      links,
      avatar,
      provenance: {
        source: 'official',
        sourceUrl: seed.sns?.[0]?.url || 'https://www.akb48.co.jp/',
        checkedAt: '2026-08-16',
        note: 'AKB48 Group verified dataset',
      },
    };
  });
}
